from symbols import (
    BULL,
    COIN,
    COLLECTOR,
    CREDIT,
    GONG,
    HOUSE,
    JACK,
    KING,
    LANTERN,
    NINE,
    QUEEN,
    TEN,
    VASE,
    YIN_YANG,
)

ROWS = 3
REELS = 5

START_BALANCE = 100
DEFAULT_BET = 1

PAYLINES = [
    [0, 0, 0, 0, 0],  # 1
    [1, 1, 1, 1, 1],  # 2
    [2, 2, 2, 2, 2],  # 3
    [0, 1, 2, 1, 0],  # 4
    [2, 1, 0, 1, 2],  # 5
    [0, 0, 1, 0, 0],  # 6
    [2, 2, 1, 2, 2],  # 7
    [1, 0, 0, 0, 1],  # 8
    [1, 2, 2, 2, 1],  # 9
    [0, 1, 1, 1, 0],  # 10
    [2, 1, 1, 1, 2],  # 11
    [1, 0, 1, 2, 1],  # 12
    [1, 2, 1, 0, 1],  # 13
    [0, 1, 0, 1, 0],  # 14
    [2, 1, 2, 1, 2],  # 15
    [0, 2, 0, 2, 0],  # 16
    [2, 0, 2, 0, 2],  # 17
    [1, 0, 2, 0, 1],  # 18
    [1, 2, 0, 2, 1],  # 19
    [0, 1, 2, 2, 1],  # 20
    [2, 1, 0, 0, 1],  # 21
    [0, 2, 1, 0, 2],  # 22
    [2, 0, 1, 2, 0],  # 23
    [1, 1, 0, 1, 1],  # 24
    [1, 1, 2, 1, 1],  # 25
]

SCATTER_PAYOUTS = {
    3: 2,
    4: 10,
    5: 50,
}

FREE_SPINS_AWARDED = {
    3: 8,
    4: 10,
    5: 12,
}

YIN_YANG_FEATURE_PAYOUTS = {
    3: (10, 30),
    4: (25, 60),
    5: (50, 120),
}

REEL_STRIPS = [
    [
        NINE,
        TEN,
        JACK,
        QUEEN,
        KING,
        GONG,
        NINE,
        TEN,
        JACK,
        HOUSE,
        QUEEN,
        TEN,
        JACK,
        LANTERN,
        NINE,
        VASE,
        TEN,
        JACK,
        BULL,
        CREDIT,
        COIN,
    ],
    [
        TEN,
        JACK,
        QUEEN,
        KING,
        NINE,
        GONG,
        TEN,
        JACK,
        HOUSE,
        COIN,
        QUEEN,
        KING,
        TEN,
        JACK,
        LANTERN,
        QUEEN,
        VASE,
        TEN,
        JACK,
        BULL,
        CREDIT,
        YIN_YANG,
    ],
    [
        JACK,
        QUEEN,
        KING,
        NINE,
        TEN,
        JACK,
        GONG,
        NINE,
        TEN,
        HOUSE,
        COIN,
        JACK,
        QUEEN,
        KING,
        NINE,
        TEN,
        LANTERN,
        JACK,
        QUEEN,
        VASE,
        TEN,
        JACK,
        BULL,
        CREDIT,
        COIN,
        YIN_YANG,
        NINE,
        TEN,
    ],
    [
        QUEEN,
        KING,
        NINE,
        TEN,
        JACK,
        GONG,
        NINE,
        TEN,
        HOUSE,
        JACK,
        QUEEN,
        KING,
        NINE,
        TEN,
        JACK,
        LANTERN,
        QUEEN,
        VASE,
        TEN,
        JACK,
        NINE,
        BULL,
        CREDIT,
        YIN_YANG,
        TEN,
        JACK,
        QUEEN,
    ],
    [
        KING,
        NINE,
        TEN,
        JACK,
        QUEEN,
        GONG,
        NINE,
        TEN,
        HOUSE,
        JACK,
        QUEEN,
        KING,
        NINE,
        TEN,
        JACK,
        LANTERN,
        QUEEN,
        VASE,
        TEN,
        JACK,
        NINE,
        BULL,
        COIN,
        COLLECTOR,
        TEN,
        JACK,
        QUEEN,
    ],
]

FREE_SPIN_REEL_STRIPS = [
    [
        NINE,
        TEN,
        JACK,
        QUEEN,
        KING,
        GONG,
        NINE,
        TEN,
        JACK,
        HOUSE,
        QUEEN,
        TEN,
        JACK,
        LANTERN,
        NINE,
        VASE,
        TEN,
        JACK,
        BULL,
        BULL,
        YIN_YANG,
    ],
    [
        TEN,
        JACK,
        QUEEN,
        KING,
        NINE,
        GONG,
        TEN,
        JACK,
        HOUSE,
        BULL,
        QUEEN,
        KING,
        TEN,
        JACK,
        LANTERN,
        QUEEN,
        VASE,
        TEN,
        JACK,
        BULL,
        YIN_YANG,
        NINE,
    ],
    [
        JACK,
        QUEEN,
        KING,
        NINE,
        TEN,
        JACK,
        GONG,
        NINE,
        TEN,
        HOUSE,
        BULL,
        JACK,
        QUEEN,
        KING,
        NINE,
        TEN,
        LANTERN,
        JACK,
        QUEEN,
        VASE,
        TEN,
        JACK,
        BULL,
        YIN_YANG,
        NINE,
        TEN,
    ],
    [
        QUEEN,
        KING,
        NINE,
        TEN,
        JACK,
        GONG,
        NINE,
        TEN,
        HOUSE,
        JACK,
        QUEEN,
        KING,
        NINE,
        TEN,
        JACK,
        LANTERN,
        QUEEN,
        VASE,
        TEN,
        JACK,
        BULL,
        YIN_YANG,
        TEN,
        JACK,
        QUEEN,
    ],
    [
        KING,
        NINE,
        TEN,
        JACK,
        QUEEN,
        GONG,
        NINE,
        TEN,
        HOUSE,
        JACK,
        QUEEN,
        KING,
        NINE,
        TEN,
        JACK,
        LANTERN,
        QUEEN,
        VASE,
        TEN,
        JACK,
        NINE,
        BULL,
        TEN,
        JACK,
        QUEEN,
    ],
]
