from symbols import BULL, COIN, DRUM, INGOT, LANTERN, YIN_YANG

ROWS = 3
REELS = 5

START_BALANCE = 1000
DEFAULT_BET = 10

REEL_STRIPS = [
    [BULL, DRUM, INGOT, LANTERN, COIN, DRUM, INGOT, YIN_YANG, LANTERN, DRUM],
    [DRUM, INGOT, BULL, LANTERN, DRUM, COIN, LANTERN, INGOT, YIN_YANG, DRUM],
    [INGOT, LANTERN, DRUM, BULL, COIN, DRUM, INGOT, LANTERN, YIN_YANG, DRUM],
    [LANTERN, DRUM, INGOT, COIN, BULL, DRUM, YIN_YANG, INGOT, LANTERN, DRUM],
    [DRUM, INGOT, LANTERN, BULL, COIN, DRUM, INGOT, YIN_YANG, LANTERN, DRUM],
]